log messages to file: C:\NatlinkGIT3\Natlink\PyTest\testresult.txt
starting unittestNatlink

starting tests with threading: 0

test recognitionMimicCommands, version: 15
validLists: ['colors']

--------------- errors -----------------

--------------- failures -----------------

---------- testRecognitionMimicCommands (__main__.UnittestNatlink) --------
Traceback (most recent call last):
  File "<string>", line 2009, in doTestCommandRecognition
natlink.MimicFailed: recognitionMimic call failed (The speech engine returned the following error: MimicNoResults)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1207, in testRecognitionMimicCommands
  File "<string>", line 2014, in doTestCommandRecognition
AssertionError: ===test failed: MimicFailed, but expected 1 (words: ['mimic', 'two', 'bllackk'])
